// Repo-wide ESLint flat config — scoped to the resupply tree only.
//
// The PennPaps fitter predates this config and is intentionally NOT linted
// here. If/when the fitter adopts ESLint, expand the `files` globs below; do
// not add a per-package eslint config (this is the single source of
// truth so the resupply-check validation step can call `eslint`
// against the whole tree in one pass).
//
// Why scoped: the resupply product's `resupply-check` validation gate
// requires lint + typecheck + test as a single signal. Linting the
// fitter in the same pass would block this gate on unrelated fitter
// drift, which is the wrong incentive for Phase 0.

import js from "@eslint/js";
import tseslint from "typescript-eslint";
import reactHooks from "eslint-plugin-react-hooks";
import globals from "globals";

export default [
  // Global ignores — never lint generated, vendored, or build output.
  {
    ignores: [
      "**/dist/**",
      "**/build/**",
      "**/node_modules/**",
      "**/.replit-artifact/**",
      "**/*.d.ts",
      // Orval-generated client code (was lib/resupply-api-client and
      // lib/api-client-react/src/generated; both folded into
      // lib/api-client-react/src/{storefront,admin}/generated by the
      // round-2 consolidation). The shape is owned by the OpenAPI specs
      // and is overwritten on every codegen run, so lint findings here
      // are not actionable. Typecheck still covers them via the lib's
      // tsconfig.
      "lib/api-client-react/src/*/generated/**",
      // Orval-generated zod schemas. The api-zod package was folded
      // into artifacts/resupply-api/src/lib/api-zod/ in the round-2
      // consolidation; the `generated/` subtree is still owned by
      // codegen and must not be hand-edited (it's regenerated whenever
      // the OpenAPI spec returns — see scripts/check-codegen.sh).
      "artifacts/resupply-api/src/lib/api-zod/generated/**",
      "scripts/check-resupply-architecture.sh.test", // bash, not JS
    ],
  },

  // Resupply TS sources — the actual scope of this config.
  {
    files: [
      "lib/resupply-*/src/**/*.ts",
      "lib/resupply-*/src/**/*.tsx",
      // resupply-api hosts the in-process pg-boss worker as of the
      // round-3 consolidation (the former artifacts/resupply-worker
      // was folded into src/worker/), so this single glob now covers
      // both the API and worker source.
      "artifacts/resupply-api/src/**/*.ts",
      // cpap-fitter SPA — added in the post-Phase-4 follow-up. Same
      // ruleset as the rest; any deviations are scoped per-file via
      // documented eslint-disable comments.
      "artifacts/cpap-fitter/src/**/*.ts",
      "artifacts/cpap-fitter/src/**/*.tsx",
      // Capacitor wrapper config — outside src/ but still owned code
      // that should be validated. Types are shim'd via
      // src/types/capacitor-cli.d.ts when @capacitor/cli isn't installed.
      "artifacts/cpap-fitter/capacitor.config.ts",
    ],
    languageOptions: {
      ecmaVersion: 2024,
      sourceType: "module",
      globals: {
        ...globals.node,
        ...globals.browser,
      },
      parser: tseslint.parser,
      parserOptions: {
        ecmaFeatures: { jsx: true },
      },
    },
    plugins: {
      "@typescript-eslint": tseslint.plugin,
      "react-hooks": reactHooks,
    },
    rules: {
      ...js.configs.recommended.rules,
      ...tseslint.configs.recommended[2].rules, // recommended (non-type-aware)
      // react-hooks plugin — load only the two classic rules:
      //   rules-of-hooks: catches conditional hook calls and similar
      //                   runtime bugs (must always be obeyed).
      //   exhaustive-deps: catches stale closures in effects/callbacks.
      // We deliberately do NOT enable v7's broader `recommended` set
      // (set-state-in-effect, refs, use-memo, purity, etc.) — those
      // rules surface real but pre-existing patterns across the
      // fitter SPA that need separate refactors, not blanket
      // suppressions. Adding them is a follow-up.
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "warn",
      // Phase 0 carve-outs — these will tighten in later phases as
      // real code lands. Listed explicitly so the deviation is visible
      // rather than silently inherited.
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      "@typescript-eslint/no-explicit-any": "warn",
      "no-empty": ["error", { allowEmptyCatch: true }],
      // TypeScript already resolves and validates identifiers (including
      // DOM types like `RequestInfo` / `HeadersInit`); ESLint's no-undef
      // can't see lib.dom.d.ts and produces false positives. Typecheck
      // is the source of truth for "is this defined".
      "no-undef": "off",
    },
  },
];
