// Repo-wide ESLint flat config — scoped to the resupply tree only.
//
// The PennPaps fitter predates this config and is intentionally NOT linted
// here. If/when the fitter adopts ESLint, expand the `files` globs below; do
// not add a per-package eslint config (this is the single source of
// truth so the resupply-check validation step can call `eslint`
// against the whole tree in one pass).
//
// Why scoped: the resupply product's `resupply-check` validation gate
// requires lint + typecheck + test as a single signal. Linting the
// fitter in the same pass would block this gate on unrelated fitter
// drift, which is the wrong incentive for Phase 0.

import js from "@eslint/js";
import tseslint from "typescript-eslint";
import reactHooks from "eslint-plugin-react-hooks";
import globals from "globals";

// Restricted-syntax entries declared at module scope so per-file overrides
// can opt OUT of one without losing the others. ESLint's `no-restricted-syntax`
// rule replaces (not merges) its options when an override block sets it, so
// every override block must re-list the entries it still wants enforced.

const RESTRICT_UPSERT_CREDENTIAL = {
  selector:
    "CallExpression[callee.type='MemberExpression'][callee.property.name='upsertCredential']",
  message:
    "Do not call repo.upsertCredential directly — use writeUserChosenPassword, writeAdminSetPassword, or rehashPasswordPreservingProvenance from lib/resupply-auth/src/credential-writes.ts so the set_by_admin_at provenance is set explicitly.",
};

// Block accidental direct `boss.createQueue(...)` calls.
//
// pg-boss v10 enforces a self-referential FK on `queue.dead_letter`: the
// DLQ row must already exist in `pgboss_resupply.queue` before the main
// queue can be inserted with that reference. `buildQueueConfig` always
// sets `deadLetter` to `${name}.dlq`, so a register function that calls
// `boss.createQueue(name, buildQueueConfig(...))` without first creating
// the `.dlq` queue will CRASH the API on first boot with
// `queue_dead_letter_fkey`. The bug stayed invisible for months because
// existing queues short-circuit the FK via `ON CONFLICT DO NOTHING`; new
// queues took the API down in May 2026.
//
// `createQueueWithDlq` in worker/lib/queue-options.ts is the only safe
// path — it creates the DLQ first, then the main queue. This rule makes
// the previous-style direct call a lint error so the next person adding
// a queue cannot quietly reintroduce the crash. Allowed exceptions are
// declared in the override block below (queue-options.ts itself, where
// `boss.createQueue` is implemented; and `*.test.ts` files that mock or
// implement the helper).
const RESTRICT_BOSS_CREATE_QUEUE = {
  selector:
    "CallExpression[callee.type='MemberExpression'][callee.property.name='createQueue']",
  message:
    "Do not call boss.createQueue directly — use createQueueWithDlq from artifacts/resupply-api/src/worker/lib/queue-options.ts so the DLQ is created before the main queue and `deadLetter` is locked to `${name}.dlq`.",
};

export default [
  // Global ignores — never lint generated, vendored, or build output.
  {
    ignores: [
      "**/dist/**",
      "**/build/**",
      "**/node_modules/**",
      "**/.replit-artifact/**",
      "**/*.d.ts",
      // Orval-generated client code (was lib/resupply-api-client and
      // lib/api-client-react/src/generated; both folded into
      // lib/api-client-react/src/{storefront,admin}/generated by the
      // round-2 consolidation). The shape is owned by the OpenAPI specs
      // and is overwritten on every codegen run, so lint findings here
      // are not actionable. Typecheck still covers them via the lib's
      // tsconfig.
      "lib/api-client-react/src/*/generated/**",
      // Orval-generated zod schemas. The api-zod package was folded
      // into artifacts/resupply-api/src/lib/api-zod/ in the round-2
      // consolidation; the `generated/` subtree is still owned by
      // codegen and must not be hand-edited (it's regenerated whenever
      // the OpenAPI spec returns — see scripts/check-codegen.sh).
      "artifacts/resupply-api/src/lib/api-zod/generated/**",
      "scripts/check-resupply-architecture.sh.test", // bash, not JS
    ],
  },

  // Resupply TS sources — the actual scope of this config.
  {
    files: [
      "lib/resupply-*/src/**/*.ts",
      "lib/resupply-*/src/**/*.tsx",
      // resupply-api hosts the in-process pg-boss worker as of the
      // round-3 consolidation (the former artifacts/resupply-worker
      // was folded into src/worker/), so this single glob now covers
      // both the API and worker source.
      "artifacts/resupply-api/src/**/*.ts",
      // cpap-fitter SPA — added in the post-Phase-4 follow-up. Same
      // ruleset as the rest; any deviations are scoped per-file via
      // documented eslint-disable comments.
      "artifacts/cpap-fitter/src/**/*.ts",
      "artifacts/cpap-fitter/src/**/*.tsx",
      // Capacitor wrapper config — outside src/ but still owned code
      // that should be validated. Types are shim'd via
      // src/types/capacitor-cli.d.ts when @capacitor/cli isn't installed.
      "artifacts/cpap-fitter/capacitor.config.ts",
    ],
    languageOptions: {
      ecmaVersion: 2024,
      sourceType: "module",
      globals: {
        ...globals.node,
        ...globals.browser,
      },
      parser: tseslint.parser,
      parserOptions: {
        ecmaFeatures: { jsx: true },
      },
    },
    plugins: {
      "@typescript-eslint": tseslint.plugin,
      "react-hooks": reactHooks,
    },
    rules: {
      ...js.configs.recommended.rules,
      ...tseslint.configs.recommended[2].rules, // recommended (non-type-aware)
      // react-hooks plugin — load only the two classic rules:
      //   rules-of-hooks: catches conditional hook calls and similar
      //                   runtime bugs (must always be obeyed).
      //   exhaustive-deps: catches stale closures in effects/callbacks.
      // We deliberately do NOT enable v7's broader `recommended` set
      // (set-state-in-effect, refs, use-memo, purity, etc.) — those
      // rules surface real but pre-existing patterns across the
      // fitter SPA that need separate refactors, not blanket
      // suppressions. Adding them is a follow-up.
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "warn",
      // Phase 0 carve-outs — these will tighten in later phases as
      // real code lands. Listed explicitly so the deviation is visible
      // rather than silently inherited.
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      "@typescript-eslint/no-explicit-any": "warn",
      "no-empty": ["error", { allowEmptyCatch: true }],
      // TypeScript already resolves and validates identifiers (including
      // DOM types like `RequestInfo` / `HeadersInit`); ESLint's no-undef
      // can't see lib.dom.d.ts and produces false positives. Typecheck
      // is the source of truth for "is this defined".
      "no-undef": "off",
      // Block accidental direct `repo.upsertCredential(...)` calls.
      //
      // `AuthRepository.upsertCredential` treats `setByAdminAt:
      // undefined` as "preserve the existing column", which silently
      // inherits a stale operator-typed timestamp onto a fresh
      // user-chosen password and trips the 7-day invite-expiry gate
      // on the user's next sign-in (locking them out of an account
      // they just reset). The three helpers in
      // `lib/resupply-auth/src/credential-writes.ts` make the
      // provenance decision impossible to forget — every new caller
      // MUST go through one of them. Allowed exceptions
      // (credential-writes.ts itself, plus the test surfaces that
      // mirror repo semantics) are scoped by the override block
      // below.
      "no-restricted-syntax": [
        "error",
        RESTRICT_UPSERT_CREDENTIAL,
        RESTRICT_BOSS_CREATE_QUEUE,
      ],
    },
  },

  // Allowed exceptions to the upsertCredential ban above. Keep this
  // list tight — every entry is a place where calling the repo
  // method directly is the correct thing to do (the three helpers
  // themselves; tests that exercise the lower-level repo contract).
  // New product code must go through credential-writes.ts. The
  // createQueue ban still applies in these files (none of them touch
  // pg-boss), so we re-list RESTRICT_BOSS_CREATE_QUEUE here.
  {
    files: [
      "lib/resupply-auth/src/credential-writes.ts",
      // Team-invite "set initial password" flow writes the
      // password_hash / set_by_admin_at columns inline against
      // Supabase rather than going through the repo, so today it
      // does not trip this rule. Whitelisted defensively so a future
      // refactor that switches it to repo.upsertCredential (an
      // intentional, audited call) does not get blocked.
      "lib/resupply-auth/src/team-invite.ts",
      "lib/resupply-auth/src/**/*.test.ts",
    ],
    rules: {
      "no-restricted-syntax": ["error", RESTRICT_BOSS_CREATE_QUEUE],
    },
  },

  // Allowed exceptions to the boss.createQueue ban above. Keep this
  // list tight — every entry is a place where calling createQueue
  // directly is correct:
  //   - queue-options.ts itself IS the safe wrapper; it has to call
  //     boss.createQueue twice (DLQ then main).
  //   - Worker job *.test.ts files mock/stub boss.createQueue (or
  //     re-implement createQueueWithDlq inside a vi.mock factory) to
  //     assert registration behavior in isolation.
  // The upsertCredential ban still applies in these files; we re-list
  // RESTRICT_UPSERT_CREDENTIAL so it is not silently dropped.
  {
    files: [
      "artifacts/resupply-api/src/worker/lib/queue-options.ts",
      "artifacts/resupply-api/src/worker/lib/queue-options.test.ts",
      "artifacts/resupply-api/src/worker/**/*.test.ts",
    ],
    rules: {
      "no-restricted-syntax": ["error", RESTRICT_UPSERT_CREDENTIAL],
    },
  },
];
