uploads = []

[[generated]]
id = "QAlpLPmgNNkL1Y4JHDyJL"
uri = "file://artifacts/cpap-fitter/src/assets/masks/full-face.png"
type = "image"
title = "generated_image"

[[generated]]
id = "iUqyiyNTSOLMES4UW_dI0"
uri = "file://artifacts/cpap-fitter/src/assets/masks/nasal.png"
type = "image"
title = "generated_image"

[[generated]]
id = "rVxTniJtCZYX-rrTtJCjS"
uri = "file://artifacts/cpap-fitter/src/assets/masks/nasal-pillow.png"
type = "image"
title = "generated_image"

[[generated]]
id = "vwsUjhLh2Qp1uT_sUMNT7"
uri = "file://artifacts/cpap-fitter/src/assets/masks/hybrid.png"
type = "image"
title = "generated_image"

[[generated]]
id = "INSet_19mx8Hl34bSsTua"
uri = "file://artifacts/penn-fit-tutorial/public/images/bg-abstract.png"
type = "image"
title = "abstract smooth light gradient background"

[[generated]]
id = "su5mOQ48j4-SJpGvmyrPA"
uri = "file://artifacts/penn-fit-tutorial/public/images/face-mesh.png"
type = "image"
title = "face wireframe tech graphic"

[[outputs]]
id = "OmkCtAOdVa_94M3hMseui"
uri = "file://outputs/pennpaps-twilio-tfv-answers.pdf"
type = "pdf"
title = "PennPaps — Twilio TFV Step 2 Answer Sheet"
