// Quarterly therapy summary — a 3-month rollup the patient can share
// with their sleep MD or insurance reviewer. HTML output that the
// browser saves to PDF; consistent with the MedWatch summary
// helper's approach.

export interface QuarterlyInput {
  patient: {
    legalFirstName: string;
    legalLastName: string;
    dateOfBirth: string | null;
  };
  /** YYYY-MM-DD bounds inclusive. */
  windowStart: string;
  windowEnd: string;
  nights: Array<{
    nightDate: string;
    usageMinutes: number | null;
    ahi: number | null;
    leakLMin: number | null;
  }>;
  practiceName: string;
}

export interface QuarterlySummary {
  fields: {
    nightsRecorded: number;
    nightsCompliant: number;
    compliancePct: number;
    avgUsageHours: number | null;
    avgAhi: number | null;
    avgLeakLMin: number | null;
  };
  html: string;
}

const COMPLIANT_MIN = 4 * 60;

export function buildQuarterlySummary(
  input: QuarterlyInput,
): QuarterlySummary {
  // Dedup by night_date — first occurrence wins (most recent ingest
  // for a date, conventionally).
  const seen = new Set<string>();
  const nights = input.nights.filter((n) => {
    if (seen.has(n.nightDate)) return false;
    seen.add(n.nightDate);
    return true;
  });

  const nightsRecorded = nights.length;
  let usageTotalMinutes = 0;
  let usageNights = 0;
  let nightsCompliant = 0;
  let ahiSum = 0;
  let ahiNights = 0;
  let leakSum = 0;
  let leakNights = 0;
  for (const n of nights) {
    if (n.usageMinutes != null) {
      usageTotalMinutes += n.usageMinutes;
      usageNights += 1;
      if (n.usageMinutes >= COMPLIANT_MIN) nightsCompliant += 1;
    }
    if (n.ahi != null) {
      ahiSum += n.ahi;
      ahiNights += 1;
    }
    if (n.leakLMin != null) {
      leakSum += n.leakLMin;
      leakNights += 1;
    }
  }
  const avgUsageHours =
    usageNights === 0
      ? null
      : Math.round((usageTotalMinutes / usageNights / 60) * 10) / 10;
  const avgAhi =
    ahiNights === 0 ? null : Math.round((ahiSum / ahiNights) * 10) / 10;
  const avgLeakLMin =
    leakNights === 0 ? null : Math.round((leakSum / leakNights) * 10) / 10;
  const compliancePct =
    nightsRecorded === 0
      ? 0
      : Math.round((nightsCompliant / nightsRecorded) * 100);

  const fields = {
    nightsRecorded,
    nightsCompliant,
    compliancePct,
    avgUsageHours,
    avgAhi,
    avgLeakLMin,
  };

  const html = renderHtml(input, fields);
  return { fields, html };
}

function renderHtml(
  input: QuarterlyInput,
  fields: QuarterlySummary["fields"],
): string {
  const name = `${input.patient.legalFirstName} ${input.patient.legalLastName}`;
  const row = (label: string, value: string): string =>
    `<tr><td style="font-weight:600;padding:6px 10px;background:#f4f4f4;border:1px solid #ddd;width:220px;">${escapeHtml(label)}</td><td style="padding:6px 10px;border:1px solid #ddd;">${escapeHtml(value)}</td></tr>`;
  return [
    `<!doctype html><html><head><meta charset="utf-8"><title>Therapy summary — ${escapeHtml(name)}</title>`,
    `<style>body{font-family:system-ui,sans-serif;max-width:780px;margin:24px auto;padding:0 16px;}h1{font-size:20px;margin-bottom:4px;}table{border-collapse:collapse;width:100%;margin:16px 0;}.banner{background:#eff6ff;border:1px solid #93c5fd;padding:10px;font-size:13px;margin:12px 0;border-radius:4px;color:#1e3a8a;}</style></head><body>`,
    `<h1>CPAP therapy summary</h1>`,
    `<div><strong>${escapeHtml(name)}</strong>${input.patient.dateOfBirth ? ` · DOB ${escapeHtml(input.patient.dateOfBirth)}` : ""}</div>`,
    `<div class="banner">Quarter window: ${escapeHtml(input.windowStart)} through ${escapeHtml(input.windowEnd)}. Generated by ${escapeHtml(input.practiceName)}.</div>`,
    `<table>`,
    row("Nights recorded", String(fields.nightsRecorded)),
    row(
      "Compliant nights (≥4 hrs)",
      `${fields.nightsCompliant} (${fields.compliancePct}%)`,
    ),
    row(
      "Average usage",
      fields.avgUsageHours == null
        ? "—"
        : `${fields.avgUsageHours.toFixed(1)} hrs/night`,
    ),
    row(
      "Average AHI",
      fields.avgAhi == null ? "—" : fields.avgAhi.toFixed(1),
    ),
    row(
      "Average leak rate",
      fields.avgLeakLMin == null
        ? "—"
        : `${fields.avgLeakLMin.toFixed(1)} L/min`,
    ),
    `</table>`,
    `<p style="color:#666;font-size:12px;">Generated by PennFit on behalf of the patient above. Do not redistribute. PHI inside.</p>`,
    `</body></html>`,
  ].join("");
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}
