// The "empty everything" body the demo sandbox returns for any GET it
// doesn't explicitly seed.
//
// The demo seeds the prominent endpoints with real fixtures; everything
// else (the long tail of admin pages a broadly-permissioned demo
// explorer can still navigate to) falls through to this shape. Returning
// a bare `{}` made those pages crash on `data.<field>.<arrayMethod>` and
// bubble to the global ErrorBoundary ("Something went wrong"); mapping
// every known collection name to an empty array (plus the common
// indexable objects and zeroed pagination) instead lets each page render
// the empty state the demo README promises. Harmless extra keys a page
// doesn't read are simply ignored. Keep this union broad — a missing
// name is a latent crash.
//
// It also backs the per-id detail handlers: when a `:id` route is hit
// with a path segment that isn't a real demo entity id (e.g. a static
// sub-route like `/patients/duplicates`), the handler returns this body
// instead of a wrong-shaped fixture.

const EMPTY_COLLECTION_KEYS = [
  "items",
  "results",
  "records",
  "rows",
  "products",
  "masks",
  "orders",
  "events",
  "messageEvents",
  "recallEvents",
  "auditEvents",
  "messages",
  "conversations",
  "patients",
  "customers",
  "tenants",
  "accounts",
  "providers",
  "previews",
  "locations",
  "agents",
  "recipients",
  "comments",
  "videos",
  "links",
  "cases",
  "closures",
  "episodes",
  "prescriptions",
  "fulfillments",
  "deliveries",
  "backorders",
  "recalls",
  "subscriptions",
  "reviews",
  "notes",
  "attachments",
  "packets",
  "interventions",
  "tasks",
  "runs",
  "rules",
  "thresholds",
  "targets",
  "requests",
  "acknowledgements",
  "signals",
  "setups",
  "signed",
  "opportunities",
  "campaigns",
  "candidates",
  "attempts",
  "addons",
  "eligible",
  "evaluated",
  "alerts",
  "points",
  "entries",
  "history",
  "activity",
  "pages",
  "sources",
  "substitutes",
  "claims",
  "insuranceClaims",
  "feeSchedules",
  "checks",
  "eraFiles",
  "groups",
  "excluded",
  "pending",
  // Real response field the earlier regex sweep could not match:
  // `pendingAgreements?: ("baa" | "platform_terms")[]` — a parenthesized
  // union element type. Flagged in review on #1260.
  "pendingAgreements",
  "queued",
  "cohort",
  "horizons",
  "funnel",
  "topMasks",
  "topRecommendations",
  "statusBreakdown",
  "ordersByDay",
  "byMonth",
  "byPlan",
  "byPayer",
  "byCohort",
  "bySource",

  // ── Drift sweep ────────────────────────────────────────────────
  // Collection names swept out of the SPA's client layer in bulk. This block
  // is deliberately BROADER than what the companion drift test
  // (empty.drift.test.ts) requires: the test derives its requirement precisely,
  // from the generic argument of each `jsonFetch<T>` call, while these were
  // gathered by a wider textual sweep. Extra names cost nothing at runtime —
  // per this file's header, a key a page never reads is simply ignored — and
  // they cover response shapes that don't flow through a typed fetch wrapper.
  // So: the TEST decides what is REQUIRED; this list may exceed it.
  // Keep alphabetical so additions diff cleanly.
  "acknowledgedDocumentKeys",
  "acknowledged_document_keys",
  "actions",
  "activeAlerts",
  "adapters",
  "admins",
  "affected",
  "agreements",
  "aliases",
  "allocations",
  "allowed",
  "allowedVariables",
  "alternatives",
  "applied_claims_json",
  "appointmentsAssignedToMe",
  "articles",
  "assets",
  "assign",
  "atRisk",
  "attemptedClaimIds",
  "autoResubmitReady",
  "awaiting",
  "batchErrors",
  "bestFor",
  "branches",
  "builderNotes",
  "bullets",
  "bundleContents",
  "byChannel",
  "byProduct",
  "byProvider",
  "categories",
  "changed",
  "changes",
  "channels",
  "children",
  "claimIds",
  "clearinghouses",
  "columns",
  "comorbidities",
  "compatibility",
  "complianceAlerts",
  "constrainedProductIds",
  "contacts",
  "content_sections",
  "contraindications",
  "conversationsAwaitingReply",
  "coverages",
  "createdIds",
  "currentProducts",
  "dayKeys",
  "defaultDiagnosisCodes",
  "defaultSections",
  "denialRateTrend",
  "deniedNeedsAnalysis",
  "details",
  "deviceClasses",
  "devices",
  "diagnoses",
  "disallowed",
  "dispositions",
  "disputes",
  "documentIds",
  "documentKeys",
  "documentOverrides",
  "documentTypes",
  "document_ids",
  "document_keys",
  "documents",
  "documentsToReview",
  "drafts",
  "eligibleNow",
  "emails",
  "endpoints",
  "episodeIds",
  "errorSamples",
  "errors",
  "expiringSoon",
  "explicitCompatibleProductIds",
  "failed",
  "failureStatuses",
  "failures",
  "features",
  "fields",
  "flags",
  "followups",
  "fulfillmentIds",
  "fulfillmentsToBill",
  "gmvCents",
  "hcpcsCodes",
  "hcpcsLines",
  "headers",
  "icd10Codes",
  "iceServers",
  "ids",
  "inboundFaxes",
  "incompleteDocuments",
  "issues",
  "lineItems",
  "lines",
  "manualPatientIds",
  "manualShopCustomerIds",
  "manufacturers",
  "members",
  "mergeTokens",
  "messaging",
  "missed",
  "missing",
  "missingDocumentIds",
  "missingFields",
  "missingProductIds",
  "modifiers",
  "newConversations",
  "newOrders",
  "newPatients",
  "newTenants",
  "nights",
  "notifications",
  "offending",
  "operators",
  "options",
  "order",
  "orderIds",
  "outcomes",
  "outreach",
  "outstanding",
  "overdueFollowups",
  "paragraphs",
  "patientDocuments",
  "payers",
  "payments",
  "pendingIds",
  "pendingReturns",
  "perPayer",
  "permissions",
  "plans",
  "present",
  "presentFields",
  "productIds",
  "providerRequests",
  "questions",
  "queue",
  "reasoning",
  "reasons",
  "reasonsForNoMatch",
  "recentNights",
  "recentOrders",
  "reconciliations",
  "recoveryCodes",
  "referrals",
  "reports",
  "required",
  "requiredClaimModifiers",
  "requiredKeys",
  "requirements",
  "returns",
  "rxRenewalsDue",
  "sample",
  "scenarios",
  "schedule",
  "scrubBlockingClaims",
  "scrubFixableClaims",
  "sections",
  "selectedKeys",
  "settings",
  "sizesAvailable",
  "skipped",
  "skippedNotReady",
  "stages",
  "statementIds",
  "statements",
  "steps",
  "submissionIds",
  "submissions",
  "subscribers",
  "substitutions",
  "supplies",
  "symptoms",
  "tags",
  "templateKeys",
  "templates",
  "tenantIds",
  "therapyLinks",
  "tickets",
  "toolCalls",
  "topPayersByOpenDollars",
  "touches",
  "types",
  "unmappedHeaders",
  "updated",
  "values",
  "variants",
  "warnings",
  "workItems",
  "appealLetters",
  "both",
  "denialCodes",
  "device",
  "encounters",
  "equipment",
  "faxes",
  "files",
  "forms",
  "insights",
  "invites",
  "macros",
  "overrides",
  "payerProfiles",
  "playbooks",
  "presets",
  "priorAuthorizations",
  "rates",
  "revisions",
  "serials",
  "specs",
  "staff",
  "studies",
  "suggestions",
  "tiers",
  "unconfiguredProductIds",
  "visits",
  "windows",
] as const;

// Object-shaped fields that pages index into (e.g. `data.counts[k]`,
// `data.stats.totalCents`) — an empty object yields `undefined` (which
// tolerant formatters handle) instead of throwing on a missing parent.
const EMPTY_OBJECT_KEYS = ["counts", "stats", "summary", "totals"] as const;

/**
 * The body returned for any unmatched (or non-owned-id) demo GET: empty
 * collections, empty indexable objects, and zeroed pagination scalars.
 * One shape that satisfies the overwhelmingly common list-page contract
 * so unseeded demo endpoints render empty states, not crashes.
 */
export function emptyGetFallbackBody(): Record<string, unknown> {
  const body: Record<string, unknown> = {
    total: 0,
    count: 0,
    page: 1,
    pageSize: 25,
    limit: 25,
    offset: 0,
  };
  for (const key of EMPTY_COLLECTION_KEYS) body[key] = [];
  for (const key of EMPTY_OBJECT_KEYS) body[key] = {};
  return body;
}
