// pg-boss job: weekly sweep of orphaned prescription-attachment PHI.
//
// Background
// ----------
// Three of the four prescription-attachment lifecycle paths are self-
// cleaning today (see docs/resupply/PHI-RETENTION.md):
//   1. Upload-url → finalize: row + bytes paired atomically.
//   2. Replacement: the previous object is deleted best-effort by the
//      api's finalize handler.
//   3. Removal: the api's DELETE handler removes bytes before
//      clearing the row's pointer columns.
// The fourth — "upload-url issued, GCS PUT happened, finalize never
// called" — leaves bytes in the bucket with no DB row pointing at
// them. This sweep is the cleanup for path #4.
//
// Algorithm
// ---------
// Once per week (Sunday 03:13 UTC):
//   1. List every object under `<entity-prefix>/uploads/` in the
//      private bucket.
//   2. SELECT every non-null `attachment_object_key` from
//      `prescriptions` (the column shape is `/objects/uploads/<uuid>`).
//   3. For each bucket object, derive its expected
//      `/objects/uploads/<uuid>` shape and look it up in the DB Set:
//        - referenced → leave alone
//        - unreferenced AND `timeCreated` is older than `graceMs`
//          (default 24h) AND a per-candidate DB recheck STILL says
//          unreferenced → delete; bump `orphans_deleted`
//        - unreferenced AND younger than the grace → leave alone
//          (might be an in-flight finalize); bump `orphans_too_young`
//        - unreferenced AND no `timeCreated` → skip-and-warn (rare
//          GCS metadata gap; safer than blind-deleting)
//   4. Emit ONE audit row summarizing the run (counters only — never
//      individual object names, which are durable joinable
//      pseudo-identifiers for the patient via the
//      `prescriptions.attachment_object_key` column they persist in).
//
// Per-candidate recheck — why
// ---------------------------
// The Set<string> of references is loaded BEFORE we list the bucket
// (saves an extra round trip on the common-case "everything is
// referenced" run). A finalize that races in between Set-build and
// the per-object decision could persist a row pointing at an object
// the sweep is about to delete. The 24h grace makes this rare, but
// "rare" PHI loss is still PHI loss. The recheck is a single
// `SELECT 1 ... LIMIT 1` per delete candidate (so practically zero
// in the steady-state where the bulk of objects are already
// referenced or already deleted), and it closes the window.
//
// PHI in logs — what we DO and DO NOT log
// ---------------------------------------
// Audit row metadata: counters ONLY. Per-object structured logs:
// counters / age buckets / classification ONLY. We deliberately do
// NOT log `object_name` anywhere — our key scheme is
// `/objects/uploads/<uuid>` where the UUID is an opaque random id
// generated by `getObjectEntityUploadURL()`. The id itself is not
// directly identifying, BUT the VALUE persists in
// `prescriptions.attachment_object_key` and joins one-hop back to
// the patient row, making the object name a durable joinable
// pseudo-identifier for the patient. The forensic value of "which
// specific object was deleted at minute X" is low for a once-a-week
// summary job; the structured logs surface enough context (counters
// and decision reason) for SOC review without persisting joinable
// identifiers.
//
// Why an audit row per RUN, not per orphan
// ----------------------------------------
// SOC reviewers need to see "retention is being enforced" at a
// glance, not 30 audit rows for one quiet weekly sweep. The summary
// row carries the counters that prove the schedule fired and how
// many orphans it cleaned up. Failures (list, ref-load, delete) are
// counted in the summary; if a deeper trace is needed, the worker's
// structured logs record per-decision reasons (without object names).
// Following the same pattern the reminders scan uses for its
// enqueue-summary audit boundary.
//
// Counters semantics
// ------------------
//   * `objects_scanned`         — total bucket objects examined.
//   * `references_loaded`       — count of non-null DB attachment keys.
//   * `orphans_deleted`         — objects deleted this run.
//   * `orphans_too_young`       — orphans skipped because of the
//                                 grace window. Will be revisited.
//   * `orphans_no_time_created` — orphans skipped because GCS did
//                                 not return a `timeCreated`. Should
//                                 be 0; non-zero means investigate.
//   * `delete_errors`           — delete attempts that threw (404
//                                 NOT counted — see policy below).
//   * `delete_404_idempotent`   — delete attempts where the object
//                                 was already gone. Treated as
//                                 success; counted separately so a
//                                 spike is visible.
//   * `recheck_saved`           — orphans the pre-delete DB recheck
//                                 reclassified as referenced (race
//                                 window detection).
//   * `non_attachment_skipped`  — bucket objects that didn't match
//                                 the expected `<entity-prefix>/uploads/`
//                                 shape. Should be 0 under normal
//                                 operation; non-zero suggests
//                                 something else is writing to the
//                                 bucket.

import { eq, isNotNull } from "drizzle-orm";
import { drizzle } from "drizzle-orm/node-postgres";
import type PgBoss from "pg-boss";

import { logAudit } from "@workspace/resupply-audit";
import { getDbPool, prescriptions } from "@workspace/resupply-db";

import { logger } from "../../lib/logger.js";
import {
  attachmentKeyForObjectName,
  deleteAttachmentObject,
  getPrivateObjectLocation,
  listAttachmentObjects,
  type AttachmentObject,
} from "../lib/object-storage.js";

// Re-export so callers (including the test suite) only need to
// import from this module — `AttachmentObject` is part of the
// sweep's public surface via `SweepDeps.listObjects`.
export type { AttachmentObject };

export const SWEEP_JOB = "prescriptions.attachment.sweep";

/** 24 hours in ms — grace period for in-flight finalize calls. */
export const DEFAULT_GRACE_MS = 24 * 60 * 60 * 1000;

/** Cron: Sunday 03:13 UTC. Weekly, off-hours, doesn't stack with the
 *  reminders scan (which runs at minute 7 of every hour). */
export const SWEEP_CRON = "13 3 * * 0";

export interface SweepCounters {
  objects_scanned: number;
  references_loaded: number;
  orphans_deleted: number;
  orphans_too_young: number;
  orphans_no_time_created: number;
  delete_errors: number;
  delete_404_idempotent: number;
  recheck_saved: number;
  non_attachment_skipped: number;
}

/** Outcome of a per-object delete attempt. The handler maps these
 *  into the right counter; isolating the values keeps the test
 *  matrix readable. */
export type DeleteOutcome = "ok" | "not_found" | "error";

export interface SweepDeps {
  asOf: Date;
  graceMs: number;
  listObjects: () => Promise<AttachmentObject[]>;
  /**
   * Resolve a bucket-listed object name to the
   * `/objects/uploads/<uuid>` shape that lives in
   * `prescriptions.attachment_object_key`. Returns null for objects
   * that don't match the attachment prefix (the sweep skips them).
   */
  attachmentKeyOf: (objectName: string) => string | null;
  loadReferencedKeys: () => Promise<Set<string>>;
  /**
   * Re-check the DB for a single attachment key right before deleting
   * its bytes. Closes the race window between the bulk
   * `loadReferencedKeys` Set-build and the per-object delete: a
   * finalize that lands in that gap would otherwise see its bytes
   * vaporised. Returns true if a `prescriptions` row currently
   * points at this key.
   */
  isStillReferenced: (attachmentKey: string) => Promise<boolean>;
  /**
   * Delete one bucket object. Returns:
   *   - "ok"        on success
   *   - "not_found" if the object was already gone (idempotent)
   *   - "error"     on any other failure (logged + counted)
   */
  deleteObject: (
    bucketName: string,
    objectName: string,
  ) => Promise<DeleteOutcome>;
  audit: (counters: SweepCounters) => Promise<void>;
}

/**
 * Pure sweep core. Every I/O dependency is injected so the test
 * suite can drive the full decision tree without standing up a
 * GCS bucket or a Postgres pool.
 *
 * Logging policy: every log line uses counters / classification /
 * age-bucket only. Object names are NEVER logged (they embed the
 * patient UUID via our `/objects/uploads/<uuid>` scheme).
 */
export async function sweepOrphans(deps: SweepDeps): Promise<SweepCounters> {
  const counters: SweepCounters = {
    objects_scanned: 0,
    references_loaded: 0,
    orphans_deleted: 0,
    orphans_too_young: 0,
    orphans_no_time_created: 0,
    delete_errors: 0,
    delete_404_idempotent: 0,
    recheck_saved: 0,
    non_attachment_skipped: 0,
  };

  const referenced = await deps.loadReferencedKeys();
  counters.references_loaded = referenced.size;

  const objects = await deps.listObjects();
  counters.objects_scanned = objects.length;

  for (const obj of objects) {
    const key = deps.attachmentKeyOf(obj.objectName);
    if (key === null) {
      counters.non_attachment_skipped += 1;
      logger.warn(
        "attachment-sweep: bucket object outside attachments prefix — skipping (object name suppressed for PHI hygiene)",
      );
      continue;
    }
    if (referenced.has(key)) {
      // Healthy — DB and bucket agree.
      continue;
    }
    if (obj.timeCreated == null) {
      // Rare: GCS basically always populates timeCreated. Skip-and-
      // warn is safer than blind delete; an alert on this counter
      // tells operators to investigate.
      counters.orphans_no_time_created += 1;
      logger.warn(
        "attachment-sweep: orphan has no timeCreated — skipping (investigate if persistent)",
      );
      continue;
    }
    const ageMs = deps.asOf.getTime() - obj.timeCreated.getTime();
    if (ageMs < deps.graceMs) {
      counters.orphans_too_young += 1;
      logger.info(
        { age_ms: ageMs, grace_ms: deps.graceMs },
        "attachment-sweep: orphan within grace window — leaving for next run",
      );
      continue;
    }
    // Pre-delete recheck — close the race between the bulk Set load
    // and this per-object decision. A finalize that landed in
    // between will show up here.
    const stillReferenced = await deps.isStillReferenced(key);
    if (stillReferenced) {
      counters.recheck_saved += 1;
      logger.info(
        { age_ms: ageMs },
        "attachment-sweep: pre-delete recheck reclassified candidate as referenced — leaving alone",
      );
      continue;
    }
    const outcome = await deps.deleteObject(obj.bucketName, obj.objectName);
    if (outcome === "ok") {
      counters.orphans_deleted += 1;
      logger.info(
        { age_ms: ageMs },
        "attachment-sweep: deleted orphan attachment",
      );
    } else if (outcome === "not_found") {
      // Already gone — likely a parallel manual delete or a previous
      // sweep run that crashed mid-cleanup. Idempotent success.
      counters.delete_404_idempotent += 1;
      logger.info(
        { age_ms: ageMs },
        "attachment-sweep: orphan already absent at delete time — counting as idempotent success",
      );
    } else {
      counters.delete_errors += 1;
      logger.error(
        { age_ms: ageMs },
        "attachment-sweep: failed to delete orphan attachment (object name suppressed for PHI hygiene)",
      );
    }
  }

  await deps.audit(counters);
  return counters;
}

export interface SweepJobData {
  /** Optional ISO timestamp the sweep should treat as "now". Used by
   *  tests / one-off backfills. Production cron leaves it absent. */
  asOfIso?: string;
  /** Optional override for the 24h grace window, in ms. */
  graceMs?: number;
}

/**
 * Build the production `SweepDeps` (real GCS, real DB, real audit).
 * Exported so an operator can call the sweep ad-hoc from a one-off
 * script without going through pg-boss.
 *
 * `deleteObject` translates a thrown 404 from GCS into the
 * `not_found` outcome so the handler can count it as idempotent
 * success rather than an error.
 */
export function buildProductionSweepDeps(
  asOf: Date,
  graceMs: number,
): SweepDeps {
  const pool = getDbPool();
  const db = drizzle(pool);
  return {
    asOf,
    graceMs,
    listObjects: () => listAttachmentObjects(),
    attachmentKeyOf: (n) => attachmentKeyForObjectName(n),
    loadReferencedKeys: async () => {
      const rows = await db
        .select({ key: prescriptions.attachmentObjectKey })
        .from(prescriptions)
        .where(isNotNull(prescriptions.attachmentObjectKey));
      const set = new Set<string>();
      for (const r of rows) {
        if (r.key) set.add(r.key);
      }
      return set;
    },
    isStillReferenced: async (attachmentKey) => {
      const rows = await db
        .select({ id: prescriptions.id })
        .from(prescriptions)
        .where(eq(prescriptions.attachmentObjectKey, attachmentKey))
        .limit(1);
      return rows.length > 0;
    },
    deleteObject: async (bucketName, objectName) => {
      try {
        await deleteAttachmentObject(bucketName, objectName);
        return "ok";
      } catch (err) {
        // GCS throws an error with `code === 404` when the object is
        // already gone. Mirror the api-side `ObjectNotFoundError`
        // policy from the DELETE handler: a missing object is a
        // successful delete.
        const code = (err as { code?: number }).code;
        if (code === 404) return "not_found";
        return "error";
      }
    },
    audit: async (counters) => {
      await logAudit({
        action: "prescription.attachment.sweep",
        adminEmail: null,
        adminUserId: null,
        targetTable: "prescriptions",
        targetId: null,
        metadata: { ...counters },
      });
    },
  };
}

/**
 * Register the sweep queue, handler, and weekly schedule. Idempotent
 * — pg-boss `createQueue` and `schedule` are upsert-style.
 *
 * Boot-time PRIVATE_OBJECT_DIR validation: a missing or malformed env
 * var should fail the worker boot, not a job 7 days later. Calling
 * `getPrivateObjectLocation()` here lets the registration throw if
 * the env is unusable, which `index.ts` translates into a fatal +
 * exit(1).
 */
export async function registerPrescriptionAttachmentSweepJob(
  boss: PgBoss,
): Promise<void> {
  // Fail fast on misconfigured object storage. The shim function
  // throws a clear error; surfacing it at registration time is much
  // better than letting the job blow up at the cron tick.
  getPrivateObjectLocation();

  await boss.createQueue(SWEEP_JOB);

  await boss.work<SweepJobData>(SWEEP_JOB, async (jobs) => {
    const data = jobs[0]?.data ?? {};
    const asOf = data.asOfIso ? new Date(data.asOfIso) : new Date();
    const graceMs = data.graceMs ?? DEFAULT_GRACE_MS;
    // Let listObjects / loadReferencedKeys / audit failures propagate
    // — pg-boss will mark the run failed, the worker's error handler
    // will log it, and SOC will see the gap in the audit-row summary
    // for that week. Silently swallowing here would hide a broken
    // sweep from the only place it's visible.
    const counters = await sweepOrphans(buildProductionSweepDeps(asOf, graceMs));
    logger.info(
      { ...counters, grace_ms: graceMs },
      "attachment-sweep: run complete",
    );
  });

  await boss.schedule(SWEEP_JOB, SWEEP_CRON);
  logger.info(
    { cron: SWEEP_CRON },
    "prescriptions.attachment.sweep scheduled",
  );
}
