import type { OwnerAnalyticsResponse } from "@workspace/api-client-react/admin";

export function ownerAnalyticsFixture(): OwnerAnalyticsResponse {
  const period = {
    patientsAdded: 0,
    orderRequestsCreated: 0,
    orderRequestsSigned: 0,
    episodesOpened: 0,
    episodesConfirmed: 0,
    episodesFulfilled: 0,
    episodesAssumedShipped: 0,
    fulfillmentLinesQueued: 0,
    unitsQueued: 0,
    shipmentLinesRecorded: 0,
    patientsServed: 0,
    returningPatientsServed: 0,
    claimsCreated: 0,
    claimBilledCents: 0,
    claimPaidToDateCents: 0,
    fitRequestsCreated: 0,
    fitRequestsFulfilled: 0,
    outboundMessages: 0,
    inboundMessages: 0,
    deliveredMessages: 0,
    failedMessages: 0,
  };
  return {
    generatedAt: "2026-09-14T12:00:00.000Z",
    window: {
      from: "2026-08-15T12:00:00.000Z",
      to: "2026-09-14T12:00:00.000Z",
      previousFrom: "2026-07-16T12:00:00.000Z",
      previousTo: "2026-08-15T12:00:00.000Z",
    },
    business: {
      status: "available",
      data: {
        current: {
          ...period,
          patientsAdded: 12,
          orderRequestsCreated: 8,
          orderRequestsSigned: 5,
          shipmentLinesRecorded: 4,
          patientsServed: 3,
          returningPatientsServed: 1,
          unitsQueued: 14,
        },
        previous: { ...period, patientsAdded: 9 },
        snapshot: {
          activePatients: 40,
          pausedPatients: 2,
          openConversations: 3,
          awaitingStaffConversations: 2,
          unassignedConversations: 1,
          overdueSlaConversations: 1,
          dueResupplyPatients: 7,
          dueSoonResupplyPatients: 4,
          addressHoldEpisodes: 0,
          pendingSignatures: 2,
          expiredSignatures: 1,
          unbilledShipmentLines: 2,
          draftClaims: 1,
          deniedClaims: 1,
          unacknowledgedClaims: 0,
          openClaims: 2,
          openClaimBilledCents: 50000,
          openClaimPaidCents: 30000,
          openFitRequests: 2,
          activeProducts: 10,
          trackedProducts: 7,
          untrackedProducts: 3,
          lowStockProducts: 1,
          outOfStockProducts: 1,
        },
        daily: [
          {
            date: "2026-09-14",
            orderRequestsCreated: 8,
            orderRequestsSigned: 5,
            episodesOpened: 6,
            shipmentLinesRecorded: 4,
            patientsAdded: 12,
          },
        ],
        orderRequestStages: [{ status: "signed", count: 5 }],
        resupplyStages: [{ status: "awaiting_response", count: 3 }],
        claimStages: [
          { status: "denied", count: 1, billedCents: 10000, paidCents: 0 },
        ],
        claimAging: [
          { bucket: "31_60", count: 1, billedCents: 10000, paidCents: 0 },
        ],
        payers: [
          {
            payer: "Synthetic payer",
            claims: 3,
            billedCents: 45000,
            paidCents: 30000,
            deniedClaims: 1,
          },
        ],
        topProducts: [
          {
            sku: "MASK-A",
            name: "Example mask",
            units: 14,
            fulfillmentLines: 4,
          },
        ],
        lowStock: [
          { sku: "MASK-A", name: "Example mask", stockCount: 0, threshold: 2 },
        ],
        outreachChannels: [
          { channel: "sms", inbound: 1, outbound: 3, delivered: 2, failed: 1 },
        ],
      },
    },
    financial: {
      status: "available",
      data: {
        current: {
          revenueCents: 10000,
          costCents: 6000,
          eventCount: 3,
          revenueEventCount: 1,
          costEventCount: 2,
          quoteCount: 1,
        },
        previous: {
          revenueCents: 8000,
          costCents: 5500,
          eventCount: 3,
          revenueEventCount: 1,
          costEventCount: 2,
          quoteCount: 1,
        },
        settled: {
          boundOrders: 5,
          settledOrders: 2,
          incompleteOrders: 3,
          uncertainOrders: 1,
          costsIncompleteOrders: 2,
          revenueIncompleteOrders: 2,
          netRevenueCents: 50000,
          netCostCents: 30000,
          contributionCents: 20000,
        },
        quality: { undatedEvents: 1, futureDatedEvents: 2 },
        pricing: {
          pendingApprovals: 1,
          openProposals: 1,
          enabled: true,
          enforceQuotes: false,
          policyConfigured: true,
          activePriceListConfigured: false,
        },
        daily: [
          {
            date: "2026-09-14",
            revenueCents: 10000,
            costCents: 6000,
            eventCount: 3,
          },
        ],
        costSources: [
          { source: "supplier_invoice", costCents: 6000, eventCount: 2 },
        ],
      },
    },
  };
}
