// auth.sessions — server-issued opaque session tokens.
//
// The raw token is generated by `lib/resupply-auth` (32 random bytes,
// base64url) and sent to the browser as the `pf_session` cookie.
// We persist `sha256(token)` only — the raw bytes never touch the
// database. On lookup we hash the cookie value and SELECT by
// `token_hash`. That way a database leak doesn't yield session
// hijacking material.
//
// Sliding expiry: every successful authed request bumps
// `last_seen_at` and pushes `expires_at` forward. Sign-out flips
// `revoked_at`; a password change revokes every row for the user.

import { sql } from "drizzle-orm";
import { customType, index, text, timestamp } from "drizzle-orm/pg-core";

import { authSchema } from "./_schema";
import { authUsers } from "./users";

// drizzle-orm doesn't ship a built-in bytea or inet helper before
// 0.46; declare them via customType so the schema stays dialect-
// accurate. Callers always pass / receive Buffer for bytea and
// string for inet.
const byteaType = customType<{ data: Buffer; driverData: Buffer }>({
  dataType() {
    return "bytea";
  },
});
const inetType = customType<{ data: string; driverData: string }>({
  dataType() {
    return "inet";
  },
});

export const authSessions = authSchema.table(
  "sessions",
  {
    id: text("id")
      .primaryKey()
      .default(sql`gen_random_uuid()::text`),
    /** sha256(rawToken). UNIQUE so a forged duplicate would fail-fast. */
    tokenHash: byteaType("token_hash").notNull().unique(),
    userId: text("user_id")
      .notNull()
      .references(() => authUsers.id, { onDelete: "cascade" }),
    issuedAt: timestamp("issued_at", { withTimezone: true })
      .notNull()
      .default(sql`now()`),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    lastSeenAt: timestamp("last_seen_at", { withTimezone: true })
      .notNull()
      .default(sql`now()`),
    revokedAt: timestamp("revoked_at", { withTimezone: true }),
    /** Best-effort observability. Never trusted for auth decisions. */
    ip: inetType("ip"),
    /** sha256 of the User-Agent. Lets "this device" stay stable
     * across small UA changes without storing the full string. */
    userAgentHash: byteaType("user_agent_hash"),
  },
  (t) => ({
    userIdx: index("auth_sessions_user_idx").on(t.userId, t.revokedAt),
    expiresIdx: index("auth_sessions_expires_idx").on(t.expiresAt),
  }),
);

// Export bytea/inet builders so the migration helper or callers can
// reuse the same custom types without redefining them.
export const byteaColumn = byteaType;
export const inetColumn = inetType;

export type AuthSessionRow = typeof authSessions.$inferSelect;
export type InsertAuthSessionRow = typeof authSessions.$inferInsert;
