import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";
import path from "path";
import runtimeErrorOverlay from "@replit/vite-plugin-runtime-error-modal";

const rawPort = process.env.PORT;

if (!rawPort) {
  throw new Error(
    "PORT environment variable is required but was not provided.",
  );
}

const port = Number(rawPort);

if (Number.isNaN(port) || port <= 0) {
  throw new Error(`Invalid PORT value: "${rawPort}"`);
}

const basePath = process.env.BASE_PATH;

if (!basePath) {
  throw new Error(
    "BASE_PATH environment variable is required but was not provided.",
  );
}

/**
 * Vite normalizes `base` to a trailing-slash form (e.g. `/resupply/`). When
 * a browser visits the bare base (`/resupply`, no trailing slash), Vite's
 * default response is a plain-text "did you mean /resupply/ instead?"
 * message rather than a redirect — which is hostile UX, especially when
 * the URL is generated by a parent frame or a typed link. This plugin
 * intercepts the bare-base request and 302-redirects to the trailing-slash
 * form, preserving any querystring. It runs in both dev and preview
 * servers so the behavior is identical between local and built output.
 */
const baseWithSlash = basePath.endsWith("/") ? basePath : `${basePath}/`;
const baseWithoutSlash = baseWithSlash.replace(/\/$/, "");

const baseTrailingSlashRedirect = {
  name: "resupply-dashboard:base-trailing-slash-redirect",
  configureServer(server: import("vite").ViteDevServer) {
    server.middlewares.use((req, res, next) => {
      if (!req.url || baseWithoutSlash === "") return next();
      const [pathOnly, search] = req.url.split("?", 2);
      if (pathOnly === baseWithoutSlash) {
        res.statusCode = 302;
        res.setHeader(
          "Location",
          `${baseWithSlash}${search ? `?${search}` : ""}`,
        );
        res.end();
        return;
      }
      next();
    });
  },
  configurePreviewServer(server: import("vite").PreviewServer) {
    server.middlewares.use((req, res, next) => {
      if (!req.url || baseWithoutSlash === "") return next();
      const [pathOnly, search] = req.url.split("?", 2);
      if (pathOnly === baseWithoutSlash) {
        res.statusCode = 302;
        res.setHeader(
          "Location",
          `${baseWithSlash}${search ? `?${search}` : ""}`,
        );
        res.end();
        return;
      }
      next();
    });
  },
};

export default defineConfig({
  base: basePath,
  plugins: [
    baseTrailingSlashRedirect,
    react(),
    tailwindcss(),
    runtimeErrorOverlay(),
    ...(process.env.NODE_ENV !== "production" &&
    process.env.REPL_ID !== undefined
      ? [
          await import("@replit/vite-plugin-cartographer").then((m) =>
            m.cartographer({
              root: path.resolve(import.meta.dirname, ".."),
            }),
          ),
          await import("@replit/vite-plugin-dev-banner").then((m) =>
            m.devBanner(),
          ),
        ]
      : []),
  ],
  resolve: {
    alias: {
      "@": path.resolve(import.meta.dirname, "src"),
      "@assets": path.resolve(import.meta.dirname, "..", "..", "attached_assets"),
    },
    dedupe: ["react", "react-dom"],
  },
  root: path.resolve(import.meta.dirname),
  build: {
    outDir: path.resolve(import.meta.dirname, "dist/public"),
    emptyOutDir: true,
  },
  server: {
    port,
    strictPort: true,
    host: "0.0.0.0",
    allowedHosts: true,
    fs: {
      strict: true,
    },
  },
  preview: {
    port,
    host: "0.0.0.0",
    allowedHosts: true,
  },
});
